In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
cartoes = pd.read_csv('campeonato-brasileiro-cartoes.csv')
estatisticas_completas = pd.read_csv("campeonato-brasileiro-estatisticas-full.csv")
jogos = pd.read_csv("campeonato-brasileiro-full.csv")
gols = pd.read_csv("campeonato-brasileiro-gols.csv")

In [4]:
cartoes.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
1,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
2,4608,1,Internacional,Amarelo,Juan Silveira dos Santos,4.0,Zagueiro,20
3,4608,1,Vitoria,Amarelo,Vinícius Santos Silva,NaN,NaN,82
4,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72

In [5]:
estatisticas_completas.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Flamengo,0,0,NaN,0,NaN,0,0,0,0,0

In [6]:
jogos.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,NaN
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,NaN

In [7]:
gols.head()

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
0,4607,1,Fluminense,Rafael Sóbis,31,NaN
1,4607,1,Fluminense,Fred,45,Penalty
2,4607,1,Fluminense,Nirley da Silva Fonseca,59,Gol Contra
3,4608,1,Internacional,Charles Aránguiz,6,NaN
4,4612,1,Cruzeiro,Marcelo Moreno,90,NaN

In [8]:
print(jogos.shape)
print(estatisticas_completas.shape)
print(gols.shape)
print(cartoes.shape)

(9165, 17)
(18330, 13)
(10820, 6)
(20953, 8)

In [9]:
print(f'{jogos.isna().sum()}\n')
print(f'{estatisticas_completas.isna().sum()}\n')
print(f'{gols.isna().sum()}\n')
print(f'{cartoes.isna().sum()}')

ID                       0
rodata                   0
data                     0
hora                     0
mandante                 0
visitante                0
formacao_mandante     4975
formacao_visitante    4975
tecnico_mandante      4610
tecnico_visitante     4610
vencedor                 0
arena                    0
mandante_Placar          0
visitante_Placar         0
mandante_Estado          0
visitante_Estado         0
arrecadacao           8785
dtype: int64

partida_id             0
rodata                 0
clube                  0
chutes                 0
chutes_no_alvo         0
posse_de_bola      10762
passes                 0
precisao_passes    13066
faltas                 0
cartao_amarelo         0
cartao_vermelho        0
impedimentos           0
escanteios             0
dtype: int64

partida_id        0
rodata            0
clube             0
atleta            0
minuto            0
tipo_de_gol    9527
dtype: int64

partida_id       0
rodata           0
clube            0
cartao           0
atleta           6
num_camisa     386
posicao       1198
minuto           0
dtype: int64

In [10]:
print(jogos["rodata"].value_counts().sort_index())

rodata
1     235
2     235
3     235
4     235
5     235
6     235
7     235
8     235
9     235
10    235
11    235
12    235
13    235
14    234
15    236
16    235
17    235
18    235
19    235
20    235
21    235
22    235
23    235
24    235
25    235
26    235
27    235
28    235
29    235
30    235
31    235
32    235
33    235
34    235
35    235
36    235
37    235
38    234
39     35
40     35
41     35
42     35
43     24
44     24
45     24
46     24
Name: count, dtype: int64

In [12]:
jogos["data"] = pd.to_datetime(jogos["data"], dayfirst=True)

jogos["temporada"] = jogos["data"].dt.year

In [13]:
stats_ano = estatisticas_completas.merge(
    jogos[["ID", "temporada"]],
    left_on="partida_id",
    right_on="ID",
    how="left"
)

In [14]:
nulos_por_ano =stats_ano.groupby("temporada")[["posse_de_bola", "precisao_passes"]].apply(lambda x: x.isna().sum())

print(nulos_por_ano)

           posse_de_bola  precisao_passes
temporada
2003                1104             1104
2004                1104             1104
2005                 924              924
2006                 760              760
2007                 760              760
2008                 760              760
2009                 760              760
2010                 760              760
2011                 760              760
2012                 760              760
2013                 760              760
2014                 728              760
2015                   0              760
2016                   0              758
2017                   2              760
2018                   0                0
2019                  46               46
2020                   2                2
2021                   0                0
2022                   0                0
2023                   0                0
2024                 760              760
2025                  12                8

In [15]:
jogos_analise = jogos.copy()
stats_analise = estatisticas_completas.copy()

In [17]:
jogos_analise["data"] = pd.to_datetime(jogos_analise["data"], dayfirst=True)

In [18]:
jogos_analise["temporada"] = jogos_analise["data"].dt.year

In [19]:
temporadas = list(range(2015, 2024)) + [2025]

In [20]:
jogos_analise = jogos_analise[jogos_analise["temporada"].isin(temporadas)].copy()

In [21]:
jogos_analise.shape

(3799, 18)

In [22]:
jogos_analise['temporada'].value_counts().sort_index()

temporada
2015    380
2016    379
2017    380
2018    380
2019    380
2020    268
2021    492
2022    380
2023    380
2025    380
Name: count, dtype: int64

In [23]:
jogos_analise["temporada"] = jogos_analise["data"].dt.year

In [24]:
jogos_analise.loc[(jogos_analise["data"] <= "2021-02-28") &(jogos_analise["data"] >= "2021-01-01"),"temporada"] = 2020

In [25]:
temporadas = list(range(2015, 2024)) + [2025]

In [26]:
jogos_analise = jogos_analise[jogos_analise["temporada"].isin(temporadas)].copy()

In [28]:
jogos_analise.shape

(3799, 18)

In [29]:
jogos_analise['temporada'].value_counts().sort_index()

temporada
2015    380
2016    379
2017    380
2018    380
2019    380
2020    380
2021    380
2022    380
2023    380
2025    380
Name: count, dtype: int64

In [30]:
colunas_stats = [
    "partida_id",
    "clube",
    "chutes",
    "chutes_no_alvo",
    "posse_de_bola",
    "passes",
    "faltas",
    "cartao_amarelo",
    "cartao_vermelho",
    "impedimentos",
    "escanteios"
]

In [31]:
stats_analise = stats_analise[colunas_stats].copy()

In [32]:
stats_analise.head()

,partida_id,clube,chutes,chutes_no_alvo,posse_de_bola,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,Vasco,0,0,NaN,0,0,0,0,0,0
1,1,Guarani,0,0,NaN,0,0,0,0,0,0
2,2,Athletico-PR,0,0,NaN,0,0,0,0,0,0
3,2,Gremio,0,0,NaN,0,0,0,0,0,0
4,3,Flamengo,0,0,NaN,0,0,0,0,0,0

In [33]:
stats_analise.shape

(18330, 11)

In [34]:
ids_partidas = jogos_analise["ID"]

In [35]:
stats_analise = stats_analise[stats_analise["partida_id"].isin(ids_partidas)].copy()

In [36]:
stats_analise.shape

(7598, 11)

In [37]:
stats_mandante = stats_analise.merge(jogos_analise[["ID", "mandante"]],left_on=["partida_id", "clube"],right_on=["ID", "mandante"],how="inner")

In [38]:
stats_mandante.shape

(3799, 13)

In [39]:
stats_mandante.head()

,partida_id,clube,chutes,chutes_no_alvo,posse_de_bola,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios,ID,mandante
0,4987,Chapecoense,13,0,45%,326,20,2,0,3,3,4987,Chapecoense
1,4988,Palmeiras,17,0,50%,406,20,2,0,2,11,4988,Palmeiras
2,4989,Fluminense,26,11,74%,702,9,2,0,1,5,4989,Fluminense
3,4990,Gremio,11,0,45%,401,17,3,0,2,5,4990,Gremio
4,4993,Cruzeiro,13,0,56%,487,17,3,0,4,2,4993,Cruzeiro

In [40]:
stats_visitante = stats_analise.merge(jogos_analise[["ID", "visitante"]],left_on=["partida_id", "clube"],right_on=["ID", "visitante"],how="inner")

In [41]:
stats_visitante.shape

(3799, 13)

In [42]:
stats_visitante.head()

,partida_id,clube,chutes,chutes_no_alvo,posse_de_bola,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios,ID,visitante
0,4987,Coritiba,16,0,55%,388,21,2,0,0,5,4987,Coritiba
1,4988,Atletico-MG,10,0,50%,426,14,4,0,4,2,4988,Atletico-MG
2,4989,Joinville,3,0,26%,250,14,0,1,1,3,4989,Joinville
3,4990,Ponte Preta,17,0,55%,473,21,4,1,0,10,4990,Ponte Preta
4,4993,Corinthians,11,0,44%,391,15,1,0,2,4,4993,Corinthians

In [43]:
stats_mandante = stats_mandante.rename(
    columns={
        "chutes": "chutes_mandante",
        "chutes_no_alvo": "chutes_no_alvo_mandante",
        "posse_de_bola": "posse_mandante",
        "passes": "passes_mandante",
        "faltas": "faltas_mandante",
        "cartao_amarelo": "cartao_amarelo_mandante",
        "cartao_vermelho": "cartao_vermelho_mandante",
        "impedimentos": "impedimentos_mandante",
        "escanteios": "escanteios_mandante"
    }
)

In [44]:
stats_mandante.columns.tolist()

['partida_id',
 'clube',
 'chutes_mandante',
 'chutes_no_alvo_mandante',
 'posse_mandante',
 'passes_mandante',
 'faltas_mandante',
 'cartao_amarelo_mandante',
 'cartao_vermelho_mandante',
 'impedimentos_mandante',
 'escanteios_mandante',
 'ID',
 'mandante']

In [45]:
stats_visitante = stats_visitante.rename(
    columns={
        "chutes": "chutes_visitante",
        "chutes_no_alvo": "chutes_no_alvo_visitante",
        "posse_de_bola": "posse_visitante",
        "passes": "passes_visitante",
        "faltas": "faltas_visitante",
        "cartao_amarelo": "cartao_amarelo_visitante",
        "cartao_vermelho": "cartao_vermelho_visitante",
        "impedimentos": "impedimentos_visitante",
        "escanteios": "escanteios_visitante"
    }
)

In [46]:
stats_visitante.columns.tolist()

['partida_id',
 'clube',
 'chutes_visitante',
 'chutes_no_alvo_visitante',
 'posse_visitante',
 'passes_visitante',
 'faltas_visitante',
 'cartao_amarelo_visitante',
 'cartao_vermelho_visitante',
 'impedimentos_visitante',
 'escanteios_visitante',
 'ID',
 'visitante']

In [48]:
df_analise = jogos_analise[["ID","temporada","rodata","data","hora","mandante","visitante","mandante_Placar","visitante_Placar"]].copy()

In [52]:
df_analise = df_analise.rename(columns={"ID": "partida_id","mandante_Placar": "gols_mandante","visitante_Placar": "gols_visitante", "rodata": "rodada" })

In [53]:
df_analise.shape

(3799, 9)

In [54]:
df_analise.head()

,partida_id,temporada,rodada,data,hora,mandante,visitante,gols_mandante,gols_visitante
4986,4987,2015,1,2015-05-09,18:32,Chapecoense,Coritiba,2,1
4987,4988,2015,1,2015-05-09,18:33,Palmeiras,Atletico-MG,2,2
4988,4989,2015,1,2015-05-09,21:00,Fluminense,Joinville,1,0
4989,4990,2015,1,2015-05-10,11:00,Gremio,Ponte Preta,3,3
4990,4993,2015,1,2015-05-10,15:59,Cruzeiro,Corinthians,0,1

In [55]:
df_analise = df_analise.merge(stats_mandante[[
            "partida_id",
            "chutes_mandante",
            "chutes_no_alvo_mandante",
            "posse_mandante",
            "passes_mandante",
            "faltas_mandante",
            "cartao_amarelo_mandante",
            "cartao_vermelho_mandante",
            "impedimentos_mandante",
            "escanteios_mandante"
        ]],on="partida_id",how="left")

In [57]:
df_analise.shape

(3799, 18)

In [58]:
df_analise.head()

,partida_id,temporada,rodada,data,hora,mandante,visitante,gols_mandante,gols_visitante,chutes_mandante,chutes_no_alvo_mandante,posse_mandante,passes_mandante,faltas_mandante,cartao_amarelo_mandante,cartao_vermelho_mandante,impedimentos_mandante,escanteios_mandante
0,4987,2015,1,2015-05-09,18:32,Chapecoense,Coritiba,2,1,13,0,45%,326,20,2,0,3,3
1,4988,2015,1,2015-05-09,18:33,Palmeiras,Atletico-MG,2,2,17,0,50%,406,20,2,0,2,11
2,4989,2015,1,2015-05-09,21:00,Fluminense,Joinville,1,0,26,11,74%,702,9,2,0,1,5
3,4990,2015,1,2015-05-10,11:00,Gremio,Ponte Preta,3,3,11,0,45%,401,17,3,0,2,5
4,4993,2015,1,2015-05-10,15:59,Cruzeiro,Corinthians,0,1,13,0,56%,487,17,3,0,4,2

In [59]:
df_analise = df_analise.merge(stats_visitante[[
            "partida_id",
            "chutes_visitante",
            "chutes_no_alvo_visitante",
            "posse_visitante",
            "passes_visitante",
            "faltas_visitante",
            "cartao_amarelo_visitante",
            "cartao_vermelho_visitante",
            "impedimentos_visitante",
            "escanteios_visitante"
        ]],on="partida_id",how="left")

In [60]:
df_analise.shape

(3799, 27)